"""Add original_title to films

Revision ID: 0a1d91ecaeb8
Revises: e70d87ec09f0
Create Date: 2026-01-27 12:26:28.533989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1d91ecaeb8'
down_revision: Union[str, Sequence[str], None] = 'e70d87ec09f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_title', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.drop_column('original_title')


    # ### end Alembic commands ###
