"""Add Watchlist fields to Film

Revision ID: 6b81e83b7dd3
Revises: 752244946b3c
Create Date: 2026-02-04 10:44:48.016791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b81e83b7dd3'
down_revision: Union[str, Sequence[str], None] = '752244946b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    config_columns = [c['name'] for c in inspector.get_columns('config')]
    films_columns = [c['name'] for c in inspector.get_columns('films')]

    with op.batch_alter_table('config', schema=None) as batch_op:
        if 'tmdb_api_key' not in config_columns:
            batch_op.add_column(sa.Column('tmdb_api_key', sa.String(), nullable=True))
        if 'tmdb_session_id' not in config_columns:
            batch_op.add_column(sa.Column('tmdb_session_id', sa.String(), nullable=True))
        if 'search_quality_filters' not in config_columns:
            batch_op.add_column(sa.Column('search_quality_filters', sa.String(), nullable=True))
        if 'search_translation_filters' not in config_columns:
            batch_op.add_column(sa.Column('search_translation_filters', sa.String(), nullable=True))

    with op.batch_alter_table('films', schema=None) as batch_op:
        if 'user_rating' not in films_columns:
            batch_op.add_column(sa.Column('user_rating', sa.Integer(), nullable=True))
        if 'tmdb_id' not in films_columns:
            batch_op.add_column(sa.Column('tmdb_id', sa.Integer(), nullable=True))
        if 'tmdb_media_type' not in films_columns:
            batch_op.add_column(sa.Column('tmdb_media_type', sa.String(), nullable=True))
        if 'monitored' not in films_columns:
            # Note: nullable=False might be tricky if adding to existing table with data, usually needs default.
            # But if it exists, we skip.
            batch_op.add_column(sa.Column('monitored', sa.Boolean(), server_default='false', nullable=False))
        if 'last_search' not in films_columns:
            batch_op.add_column(sa.Column('last_search', sa.DateTime(timezone=True), nullable=True))
        if 'watch_status' not in films_columns:
            batch_op.add_column(sa.Column('watch_status', sa.String(), nullable=True))
        if 'voiceover_filter' not in films_columns:
            batch_op.add_column(sa.Column('voiceover_filter', sa.String(), nullable=True))
        if 'target_size_gb' not in films_columns:
            batch_op.add_column(sa.Column('target_size_gb', sa.Float(), nullable=True))
        if 'min_size_gb' not in films_columns:
            batch_op.add_column(sa.Column('min_size_gb', sa.Float(), nullable=True))
        if 'max_size_gb' not in films_columns:
            batch_op.add_column(sa.Column('max_size_gb', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.drop_column('max_size_gb')
        batch_op.drop_column('min_size_gb')
        batch_op.drop_column('target_size_gb')
        batch_op.drop_column('voiceover_filter')
        batch_op.drop_column('watch_status')
        batch_op.drop_column('last_search')
        batch_op.drop_column('monitored')
        batch_op.drop_column('tmdb_media_type')
        batch_op.drop_column('tmdb_id')
        batch_op.drop_column('user_rating')

    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('search_translation_filters')
        batch_op.drop_column('search_quality_filters')
        batch_op.drop_column('tmdb_session_id')
        batch_op.drop_column('tmdb_api_key')

    # ### end Alembic commands ###
