"""add season and episode to torrents

Revision ID: 920906cdff50
Revises: a2f87a7c001a
Create Date: 2026-02-27 10:47:20.196052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920906cdff50'
down_revision: Union[str, Sequence[str], None] = 'a2f87a7c001a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('torrents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('episode', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('torrents', schema=None) as batch_op:
        batch_op.drop_column('episode')
        batch_op.drop_column('season')

    # ### end Alembic commands ###
