"""add per-search quality and translation filters

Revision ID: a2f87a7c001a
Revises: 116051d30fa5
Create Date: 2026-02-26 18:50:27.213903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f87a7c001a'
down_revision: Union[str, Sequence[str], None] = '116051d30fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_filters', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('translation_filters', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.drop_column('translation_filters')
        batch_op.drop_column('quality_filters')

    # ### end Alembic commands ###
