"""initial_squashed

Revision ID: e70d87ec09f0
Revises:
Create Date: 2026-01-18 15:07:24.606862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70d87ec09f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('folder', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_configured', sa.Boolean(), nullable=False),
    sa.Column('telegram_token', sa.String(), nullable=True),
    sa.Column('unauthorized_message', sa.String(), nullable=True),
    sa.Column('torrent_client', sa.String(), nullable=False),
    sa.Column('qbittorrent_host', sa.String(), nullable=False),
    sa.Column('qbittorrent_port', sa.Integer(), nullable=False),
    sa.Column('qbittorrent_username', sa.String(), nullable=False),
    sa.Column('qbittorrent_password', sa.String(), nullable=True),
    sa.Column('transmission_host', sa.String(), nullable=False),
    sa.Column('transmission_port', sa.Integer(), nullable=False),
    sa.Column('transmission_username', sa.String(), nullable=True),
    sa.Column('transmission_password', sa.String(), nullable=True),
    sa.Column('proxy', sa.String(), nullable=True),
    sa.Column('seed_ratio_limit', sa.Float(), nullable=False),
    sa.Column('seed_time_limit', sa.Integer(), nullable=False),
    sa.Column('inactive_seeding_time_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_authorized', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_tfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('films',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blake', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ru_name', sa.String(), nullable=True),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('cron', sa.String(), nullable=False),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribes',
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('search_id', 'user_id')
    )
    op.create_table('task_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('torrents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('blake', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('magnet', sa.String(), nullable=False),
    sa.Column('created', sa.Date(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('sz', sa.BigInteger(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('downloaded', sa.Boolean(), nullable=False),
    sa.Column('seeds', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('magnet')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('torrents')
    op.drop_table('task_executions')
    op.drop_table('subscribes')
    op.drop_table('searches')
    op.drop_table('films')
    op.drop_table('users')
    op.drop_table('config')
    op.drop_table('categories')
    # ### end Alembic commands ###
